### ISSUE TITLE
Excel addin returns data as string, not number (Excel beta addin v3.80.1)

### ISSUE THREAD

**Issue by gilesm2** [quandl/quandl-excel-windows#17]
Test:
=ISNUMBER(QSERIES("CURRFX/GBPUSD/RATE",42767,"daily",,,,FALSE,FALSE))
Returns FALSE; it should be TRUE.
This is GBP/USD currency data for Wednesday 1st Feb 2017, and the Quandl result is "1.2658867835999".  

These are numerical rates (and show in the graph in Quandl as numerical), but they come back as strings in Excel.  Therefore number styles (e.g. displaying to n decimal places) will not work.

**Comment by theAngeLopez** [comment]
Hello gilesm2, 

By design, QSERIES writes data directly into a cell as opposed to returning values to be used within other functions. This means that if it’s not null, it’s a string that Excel can then convert. 
This ties into why you’re getting FALSE from the query. Because QSERIES returns a string, when you call ISNUMBER on the original query, Excel hasn’t had the opportunity to convert it yet. 
For the time being, you can format the data type on the whole column in your spreadsheet or use the Excel VALUE function chained in your call as per: 
https://support.office.com/en-us/article/VALUE-function-257d0108-07dc-437d-ae1c-bc2d3953d8c2

Hope this answers your question and thanks for using our Excel Addin!
- Angel

**Comment by gilesm2** [comment]
hi Angel,
Thank you for the reply, and explaining that QSERIES is designed to write
the data directly into the cell as text, even if I think it should be a
number.

I'm using QSERIES because the (rather elegant) QDATA function was removed.
Is there a better function I should be using, which returns a number as a
typical user would expect, please?

Regards,
Giles.
